### ISSUE TITLE
Get Zone Names from Airtouch Config

### ISSUE THREAD

**Issue by noobydp** [mihailescu2m/homebridge-airtouch4-platform#2]
Hi,
Is it possible to get the zone names from the AT4 and present them in homekit instead of Zone 0, Zone 1...
I managed to pull the settings/config information from my AT4 by sending:
`55 55 80 b0 00 2f 00 02 03 ff 16 cd`

The response looked like this, with fixed character length spaces for the zone names.
Sorry if this isn't clear, I'm a bit out of my depth with this stuff.

My zone names are:

1. Living
2. Activity
3. Office
4. Master
5. Bedroom2
6. Bedroom3
7. Bedroom4
8. Bedroom5

`UU\b0\80\00/\01\c4\03\ff\19a\19(\10\00\10\10\00\00\08\81\00\00Polyaire\00\0008 8349 8466\00\00v^Polyaire\00\00\00\00\00\00\00\002\01\0c@\00\08\08\00\fd\88\1f\9c \10UNIT1\00\00\00\00\08\01\00\80\88\00\00 \10UNIT2\00\00\00\00\08\00\00\80\88\1f\1d \10UNIT3\00\00\00\00\08\00\00\80\88\1f\1d \10UNIT4\00\00\00Living\00\00ActivityOffice\00\00Master\00\00Bedroom2Bedroom3Bedroom4Bedroom5Group9\00\00GroupA\00\00GroupB\00\00GroupC\00\00GroupD\00\00GroupE\00\00GroupF\00\00GroupG\00\00\ff\ff\ff\ff\80\00LMO\00\00\00\00\00\r\00Master\00\00\08\00Off\00\00\00\00\00\00\ffOn\00\00\00\00\00\00\ff\ff\a2\00\a2\00\a2\00\a2\00\a2\00\a2\00\a2\00\a2\00@B\98\00[g\00\00\01\00\00\00\ff\e7\ff\fe\02\00\00\00\ff\e7\ff\fe\03\00\00\00\ff\e7\ff\fe@\80\18\e4[w\01d\1ed\ff\f7B\8f\18\8f\\\87\03\80\18\80] \04d\04\00\ff\e7\05d\04\00\ff\e7\06d\04\00\ff\e7\07(\15\00\ff\e7\08\00\04\00>\87\t\00\04\00>\87\n\00\04\00>\87\0b\00\04\00>\87\0c\00\04\00>\87\r\00\04\00>\87\0e\00\04\00>\87\0f\00\04\00>\87\a4\b7`

**Comment by mihailescu2m** [comment]
Yes I can get the zone names, was planning to add this feature, but I found I like more the "Zone X" name because of the Home App changes in iOS13.

The problem is that Home app already has room name prefixed for accessories, if your room is called "Bedroom2" in Homekit you would end up with "Bedroom2 Bedroom2" (whereas now it would be "Bedroom2 Zone 5")

**Comment by noobydp** [comment]
Ah ok that makes sense. 
I ended up naming mine: “Room Name AC” or similar so in the Home app it just shows “AC”
