### ISSUE TITLE
AirTouch Console Freezes

### ISSUE THREAD

**Issue by ghost** [mihailescu2m/homebridge-airtouch4-platform#3]
AirTouch control console (android) application freezes intermittently when this plugin is active. The controller app needs to be restarted and will function OK for a while before freezing again.
Removed this plugin from my Homebridge installation and 2 months without freezing issue. Reinstalled the plugin and the app froze within 2 hours.
Otherwise the plugin works well and is an excellent implementation!

**Comment by mihailescu2m** [comment]
Can you give some details on your setup? Seems like some kind of configuration mismatch. Can you check the logs on the message exchanges when you change settings from HomeKit vs when you change same settings from controller (plugin should see and print when you change settings from controller too).

**Comment by ghost** [comment]
I figured out to update Homebridge to 0.4.53 and that resolved this issue.
The thanks for the plugin - this is excellent and the temperature history in the Eve app is legendary!
