### ISSUE TITLE
Newbie Help

### ISSUE THREAD

**Issue by Rynotastic** [mihailescu2m/homebridge-airtouch4-platform#4]
Thanks so much for the plugin. I can see that home bridge has found the Airtouch and I can control it with UI-X but how do I get it to work with the home app? When I re-add the home bridge
it just wants to add a vacuum. Any help would be awesome. Do I need to set up an accessories list in config.json? If so then very much HELP

**Comment by Rynotastic** [comment]
Update: the zone controls have appeared and work great. However I don’t seem to have a way to turn the unit on or off.

**Comment by mihailescu2m** [comment]
Try installing the Eve app and see if you can find it there. Unit should be called AC0.

**Comment by Rynotastic** [comment]
Thanks for the reply. The only thing that is added that makes no sense is a switch called vacuum that is non operational. Looking at the eve app I see the same things. All of the zones and dampness are there and work. just missing the main unit. Do you have to add it in the accessories in config.json? AC0 shows up on home bridge but not HomeKit.

**Comment by mihailescu2m** [comment]
Did you manage to get it working?

**Comment by Rynotastic** [comment]
After re installing homebridge and starting fresh, yes. Flawlessly! Must have had something else stopping it. Great plugin!
